### ISSUE TITLE
[Issue]: button presses not being recognized on newest firmware 

### ISSUE THREAD

**Issue by redstone47** [sanjay900/guitar-configurator#36]
### Please describe your issue.

after updating to the newest uno firmware no button presses were registering

### Version

yes

### What operating system are you using?

Windows 11

### What microcontroller are you using?

arduino uno

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
odd, do things like pin detection work at all?

**Comment by redstone47** [comment]
yes pin detection works

**Comment by sanjay900** [comment]
I suspect this has something to do with the fact that the firmware got bigger recently, and the uno must not quite have the ram or flash space free. Im in the process of rewriting every firmware from scratch, so that should fix this issue once and for all as the new firmware is much smaller

**Comment by redstone47** [comment]
i tried to update again today because the whammy doesn't work but it still crashes guitar configurator and no button inputs are recognized

**Comment by sanjay900** [comment]
Fixed with 8.9.2
